---
# Site
baseurl: "https://www.jan-martinek.com"
title: Jan Martinek
enableRobotsTXT: true
googleAnalytics: "UA-563461-2"
# Content
languageCode: "en-us"
defaultContentLanguage: "en"
# Formats
metaDataFormat: "yaml"
pygmentsUseClasses: true
pygmentsCodeFences: true

params:
  author: Jan Martinek
  description: What is humane digital future like? Let's find out together. Trying to teach && learn, design && build, talk && share.
  site_description: What is humane digital future like? Let's find out together. Trying to teach && learn, design && build, talk && share.
  images: ["https://www.jan-martinek.com/img/blank.png"]

taxonomies:
  language: lang
  project: projects
  projekt: projekty
  tag: tags
  part: series

# -----------------------------
# DO NOT CHANGE BELOW THIS LINE
# -----------------------------
disableLiveReload: true
watch: false
---
